export const TALENT_DATA = [
  {
    id: 1,
    name: 'Test Project 1',
    description: 'Test description',
    skills: ['React', 'Typescript', 'Javascript'],
    experiencePoints: 120,
    hourlyRate: 30,
  },
  {
    id: 2,
    name: 'Test Project 2',
    description: 'Test description',
    skills: ['React', 'Typescript', 'Javascript'],
    experiencePoints: 120,
    hourlyRate: 30,
  },
  {
    id: 3,
    name: 'Test Project 3',
    description: 'Test description',
    skills: ['React', 'Typescript', 'Javascript'],
    experiencePoints: 120,
    hourlyRate: 30,
  },
  {
    id: 4,
    name: 'Test Project 4',
    description: 'Test description',
    skills: ['React', 'Typescript', 'Javascript'],
    experiencePoints: 120,
    hourlyRate: 30,
  },
  {
    id: 5,
    name: 'Test Project 5',
    description: 'Test description',
    skills: ['React', 'Typescript', 'Javascript'],
    experiencePoints: 120,
    hourlyRate: 30,
  },
  {
    id: 6,
    name: 'Test Project 6',
    description: 'Test description',
    skills: ['React', 'Typescript', 'Javascript'],
    experiencePoints: 120,
    hourlyRate: 30,
  },
  {
    id: 7,
    name: 'Test Project 7',
    description: 'Test description',
    skills: ['React', 'Typescript', 'Javascript'],
    experiencePoints: 120,
    hourlyRate: 30,
  },
  {
    id: 8,
    name: 'Test Project 8',
    description: 'Test description',
    skills: ['React', 'Typescript', 'Javascript'],
    experiencePoints: 120,
    hourlyRate: 30,
  },
]
