export const MOCK_DATA = [
  {
    id: 1,
    name: 'John Doe',
    role: 'Software Engineer',
    level: 1,
    projectsCompleted: 2,
    hourlyRate: 30,
    image: 'https://randomuser.me/api/portraits/men/40.jpg',
    linkedin: 'https://www.linkedin.com/in/johndoe',
    twitter: 'https://twitter.com/johndoe',
  },
  {
    id: 2,
    name: 'Joshua Green',
    role: 'Software Engineer',
    level: 1,
    projectsCompleted: 2,
    hourlyRate: 30,
    image: 'https://randomuser.me/api/portraits/men/8.jpg',
    linkedin: 'https://www.linkedin.com/in/johndoe',
    twitter: 'https://twitter.com/johndoe',
  },
  {
    id: 3,
    name: 'Candy Darling',
    role: 'Software Engineer',
    level: 1,
    projectsCompleted: 2,
    hourlyRate: 30,
    image: 'https://randomuser.me/api/portraits/women/3.jpg',
    linkedin: 'https://www.linkedin.com/in/johndoe',
    twitter: 'https://twitter.com/johndoe',
  },
  {
    id: 4,
    name: 'Olivia Daily',
    role: 'Software Engineer',
    level: 1,
    projectsCompleted: 2,
    hourlyRate: 30,
    image: 'https://randomuser.me/api/portraits/women/5.jpg',
    linkedin: 'https://www.linkedin.com/in/johndoe',
    twitter: 'https://twitter.com/johndoe',
  },
  {
    id: 5,
    name: 'Mitch Heed',
    role: 'Software Engineer',
    level: 1,
    projectsCompleted: 2,
    hourlyRate: 30,
    image: 'https://randomuser.me/api/portraits/men/30.jpg',
    linkedin: 'https://www.linkedin.com/in/johndoe',
    twitter: 'https://twitter.com/johndoe',
  },
  {
    id: 6,
    name: 'Jane Doe',
    role: 'Software Engineer',
    level: 1,
    projectsCompleted: 2,
    hourlyRate: 30,
    image: 'https://randomuser.me/api/portraits/women/30.jpg',
    linkedin: 'https://www.linkedin.com/in/johndoe',
    twitter: 'https://twitter.com/johndoe',
  },
]
